language: node_js
sudo: required
services:
  - docker
node_js:
  - "9"
before_install:
  - sudo apt-get -y install software-properties-common
  - sudo apt-get -y install python-pip
  - sudo pip install ansible==2.4.3
install:
  - npm ci
  - cd hexo && npm ci
  - cd ..
jobs:
  include:
    - stage: build the image
      script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: ./build.sh
    - stage: release the image
      script: ./release.sh
    - stage: deploy
      script: ./deploy_dgo.sh
