language: node_js
sudo: required
if: branch = master
services:
  - docker
node_js:
  - "9"
before_install:
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - sudo apt-get -y install software-properties-common
  - sudo apt-get -y install python-pip
  - sudo pip install ansible==2.4.3
install:
  - npm install -g npm
  - npm ci
  - cd hexo && npm ci
  - cd ..
jobs:
  include:
    - stage: build and release the image      
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - ./build.sh
        - ./release.sh
        - ./deploy_dgo.sh

notifications:
  email:
    recipients:
      - wumuxian1988@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
