language: node_js
sudo: required
if: branch = master
addons:
  ssh_known_hosts: 188.166.184.10
services:
- docker
node_js:
- '9'
before_install:
- openssl aes-256-cbc -K $encrypted_96021d383a7d_key -iv $encrypted_96021d383a7d_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- sudo apt-get -y install software-properties-common
- sudo apt-get -y install python-pip
- sudo pip install ansible==2.4.3
install:
- npm install -g npm
- npm ci
- cd hexo && npm ci
- cd ..
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- "./build.sh"
- "./release.sh"
before_deploy:
  - "openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d"
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy_dgo.sh
notifications:
  email:
    recipients:
    - wumuxian1988@gmail.com
    on_success: never
    on_failure: always
